### ISSUE TITLE
Error in useDidMount hook

### ISSUE THREAD

**Issue by spinzed** [AviusX/paperhub-frontend#2]
I believe that you've made a semantic error here. How can a component be initially mounted then after first render unmounted?

https://github.com/AviusX/paperhub-frontend/blob/5fa0fed3f2b209f80f5944a27530175b344765ce/src/hooks/useDidMount.ts#L4

**Comment by AviusX** [comment]
The hook doesn't mount or unmount a component. It indicates if this is the first time the component is mounted or if the component is already mounted and just re-rendered.
This hook is used in the search screen-

https://github.com/AviusX/paperhub-frontend/blob/5fa0fed3f2b209f80f5944a27530175b344765ce/src/screens/Search/Search.tsx#L30

to run a useEffect only on subsequent renders and not the first time the component gets mounted. Apparently it's currently the only way to stop a useEffect from running on component mount and only run it when the dependencies of the useEffect hook change.

You can read more about it [in this StackOverflow answer](https://stackoverflow.com/questions/55075604/react-hooks-useeffect-only-on-update).

**Comment by AviusX** [comment]
Ah I see. I did miss your point. Sorry about that. What you're saying does make sense. I'll change the code like you said along with the next change I commit.
And thank you for the comment on the tech stack :smile:
